// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedEnum.proto

#include "SharedEnum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_SharedEnum_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_SharedEnum_2eproto = nullptr;
const uint32_t TableStruct_SharedEnum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_SharedEnum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020SharedEnum.proto\022\010Protocol*\200\001\n\017EPacket"
  "Protocol\022\031\n\025PACKET_PROTOCOL_START\020\000\022\022\n\016C"
  "S_ChatRequest\020\001\022\023\n\017SC_ChatResponse\020\002\022\023\n\017"
  "CS_GetIDRequest\020\003\022\024\n\020SC_GetIDResponse\020\004*"
  "g\n\013EDBProtocol\022\025\n\021DB_PROTOCOL_START\020\000\022\024\n"
  "\020SGDB_ServerStart\020\001\022\024\n\020SGDB_ChatRequest\020"
  "\002\022\025\n\021GDBS_ChatResponse\020\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_SharedEnum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_SharedEnum_2eproto = {
    false, false, 272, descriptor_table_protodef_SharedEnum_2eproto,
    "SharedEnum.proto",
    &descriptor_table_SharedEnum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_SharedEnum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_SharedEnum_2eproto,
    file_level_service_descriptors_SharedEnum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_SharedEnum_2eproto_getter() {
  return &descriptor_table_SharedEnum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_SharedEnum_2eproto(&descriptor_table_SharedEnum_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPacketProtocol_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_SharedEnum_2eproto);
  return file_level_enum_descriptors_SharedEnum_2eproto[0];
}
bool EPacketProtocol_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EDBProtocol_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_SharedEnum_2eproto);
  return file_level_enum_descriptors_SharedEnum_2eproto[1];
}
bool EDBProtocol_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
